export const SUB_ACCOUNTS_FETCH_REQUEST = 'SUB_ACCOUNTS_FETCH_REQUEST';
export const SUB_ACCOUNTS_FETCH_SUCCESS = 'SUB_ACCOUNTS_FETCH_SUCCESS';
export const SUB_ACCOUNTS_FETCH_FAILURE = 'SUB_ACCOUNTS_FETCH_FAILURE';
export const SUB_ACCOUNTS_UPDATE = 'SUB_ACCOUNTS_UPDATE';
