export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_PARTIAL_AUTH = 'USER_PARTIAL_AUTH';
export const TOKEN_REFRESH_REQUEST = "TOKEN_REFRESH_REQUEST";
export const REFRESH_TOKEN_EXPIRATION = "REFRESH_TOKEN_EXPIRATION";
export const TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS"