const REST_PATH_AUTH = 'http://127.0.0.1:80/api/web'
const REST_PATH_ACCOUNT = 'http://127.0.0.1:80/api/account'
const REST_PATH_EXCHANGE = 'http://127.0.0.1:80/api/exchange'
const REST_PATH_TRANSFER = 'http://127.0.0.1:80/api/transfer'
const PASSWORD_MAX_LENGTH = 20
const PASSWORD_MIN_LENGTH = 10
const CODE_LENGTH = 6
const CURRENCIES = ['USD', 'PLN', 'CHF', 'GBP', 'EUR']
const DEFAULT_SELECTED_CURRENCY = 'PLN'
const TRANSFER_TYPE_RECEIVED = "RECEIVED"
const TRANSFER_TYPE_SENT = "SENT"
const BEARER_PREFIX = "Bearer "

export {
    REST_PATH_AUTH,
    REST_PATH_ACCOUNT,
    REST_PATH_EXCHANGE,
    REST_PATH_TRANSFER,
    PASSWORD_MAX_LENGTH,
    PASSWORD_MIN_LENGTH,
    CODE_LENGTH,
    CURRENCIES,
    DEFAULT_SELECTED_CURRENCY,
    TRANSFER_TYPE_RECEIVED,
    TRANSFER_TYPE_SENT,
    BEARER_PREFIX
}